name: release
on:
  release:
    types: [created]
  workflow_dispatch:

jobs:
  release:
    name: ${{ matrix.target }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: ubuntu-latest
            target: arm-unknown-linux-gnueabihf
            bin: inputshare-server
          - os: ubuntu-latest
            target: armv7-unknown-linux-gnueabihf
            bin: inputshare-server
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            bin: inputshare-client
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          override: true
          target: ${{ matrix.target }}

      - name: Build binary
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked --target=${{ matrix.target }} --bin=${{ matrix.bin }} --color=always --verbose
          use-cross: ${{ runner.os == 'Linux' }}

      - name: Package (*nix)
        if: runner.os != 'Windows'
        run: >
          tar -cv
          License.md Readme.md
          -C target/${{ matrix.target }}/release/ ${{ matrix.bin }}
          | gzip --best > '${{ matrix.bin }}-${{ matrix.target }}.tar.gz'
      - name: Package (Windows)
        if: runner.os == 'Windows'
        run: >
          7z a ${{ matrix.bin }}-${{ matrix.target }}.zip
          License.md Readme.md
          ./target/${{ matrix.target }}/release/${{ matrix.bin }}.exe
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.target }}
          path: |
            *.zip
            *.tar.gz
      - name: Create release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            *.zip
            *.tar.gz
